#include "graphics_manager.h"
#include "string.h"

#define EMPTYTILE_RAM_POS  EMPTYTILE_IDX * 32
#define FULLTILE_RAM_POS  FULLTILE_IDX * 32
#define HITTILE_RAM_POS  HITTILE_IDX * 32
#define MISSTILE_RAM_POS  MISSTILE_IDX * 32
#define EMPTYTILE2_RAM_POS EMPTYTILE2_IDX*32

typedef enum {EMPTYTILE_IDX = 0, EMPTYTILE2_IDX,  FULLTILE_IDX, HITTILE_IDX, MISSTILE_IDX} Tile_indexes ;
typedef enum {BLUE1_IDX = 0, BLUE2_IDX, BLUE3_IDX, BLUE4_IDX, BLUE5_IDX, RED_IDX, GREEN_IDX, WHITE_IDX, BLACK_IDX, CYAN_IDX, CYAN2_IDX, end}Color_indexes ;


void configure_graphics_sub(){

}

u8 empty_tile[64] = {
		 BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,
		 BLACK_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,
		 BLACK_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,
		 BLACK_IDX,  WHITE_IDX,  BLUE3_IDX,  BLUE3_IDX,  BLUE3_IDX,  BLUE3_IDX,  BLUE3_IDX,  WHITE_IDX,
		 BLACK_IDX,  BLUE4_IDX,  WHITE_IDX,  BLUE4_IDX,  BLUE4_IDX,  BLUE4_IDX,  WHITE_IDX,  BLUE4_IDX,
		 BLACK_IDX,  BLUE3_IDX,  BLUE3_IDX,  WHITE_IDX,  WHITE_IDX,  WHITE_IDX,  BLUE3_IDX,  BLUE3_IDX,
		 BLACK_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,
		 BLACK_IDX,  BLUE5_IDX,  BLUE5_IDX,  BLUE5_IDX,  BLUE5_IDX,  BLUE5_IDX,  BLUE5_IDX,  BLUE5_IDX
};

u8 hit_tile[64] = {
		 BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,
		 BLACK_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,   BLUE1_IDX,
		 BLACK_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,     BLUE2_IDX,  RED_IDX ,   RED_IDX ,   RED_IDX,
		 BLACK_IDX,  WHITE_IDX,  BLUE3_IDX,  BLUE3_IDX,    BLACK_IDX,  RED_IDX ,   RED_IDX ,   RED_IDX,
		 BLACK_IDX,  BLUE4_IDX,  BLUE4_IDX,   BLACK_IDX,   BLACK_IDX,   BLACK_IDX,  RED_IDX ,   RED_IDX ,
		 BLACK_IDX,  BLUE3_IDX,  BLUE3_IDX,   RED_IDX ,   BLACK_IDX,   BLACK_IDX, BLACK_IDX,   RED_IDX ,
		 BLACK_IDX,  BLUE2_IDX,   RED_IDX ,   RED_IDX ,    RED_IDX ,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,
		 BLACK_IDX,  BLUE5_IDX,   RED_IDX ,   RED_IDX ,    RED_IDX ,  RED_IDX ,   BLACK_IDX,   BLACK_IDX,
};
u8 full_tile[64] = {
		 BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,
		 BLACK_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,   BLUE1_IDX,
		 BLACK_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,     BLUE2_IDX,  GREEN_IDX ,   GREEN_IDX ,   GREEN_IDX,
		 BLACK_IDX,  WHITE_IDX,  BLUE3_IDX,  BLUE3_IDX,    GREEN_IDX ,  GREEN_IDX ,   GREEN_IDX ,   GREEN_IDX,
		 BLACK_IDX,  BLUE4_IDX,  BLUE4_IDX,   GREEN_IDX ,   GREEN_IDX ,    GREEN_IDX ,  GREEN_IDX ,   GREEN_IDX ,
		 BLACK_IDX,  BLUE3_IDX,  BLUE3_IDX,   GREEN_IDX ,   GREEN_IDX ,    GREEN_IDX ,  GREEN_IDX ,   GREEN_IDX ,
		 BLACK_IDX,  BLUE2_IDX,   GREEN_IDX ,   GREEN_IDX ,    GREEN_IDX ,  GREEN_IDX ,   GREEN_IDX ,   GREEN_IDX ,
		 BLACK_IDX,  BLUE5_IDX,   GREEN_IDX ,   GREEN_IDX ,    GREEN_IDX ,  GREEN_IDX ,   GREEN_IDX ,   GREEN_IDX ,
};

u8 miss_tile[64] = {
		 BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,
		 BLACK_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,
		 BLACK_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,
		 BLACK_IDX,  WHITE_IDX,  BLUE3_IDX,  BLUE3_IDX,  BLUE3_IDX,  BLUE3_IDX,  BLUE3_IDX,  WHITE_IDX,
		 BLACK_IDX,  BLUE4_IDX,  WHITE_IDX,  BLUE4_IDX,  BLUE4_IDX,  BLUE4_IDX,  BLUE2_IDX,  BLUE2_IDX,
		 BLACK_IDX,  BLUE3_IDX,  BLUE3_IDX,  WHITE_IDX,  WHITE_IDX,  BLUE2_IDX,  BLUE3_IDX,  BLUE3_IDX,
		 BLACK_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE3_IDX,  BLUE4_IDX,  BLUE4_IDX,
		 BLACK_IDX,  BLUE5_IDX,  BLUE5_IDX,  BLUE5_IDX,  BLUE2_IDX,  BLUE3_IDX,  BLUE4_IDX,  WHITE_IDX,
};

/*
u8 hit_tile[64] = {
		 BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,  BLACK_IDX,
		 BLACK_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,  BLUE1_IDX,   BLUE1_IDX,
		 BLACK_IDX,  BLUE2_IDX,  BLUE2_IDX,  BLUE2_IDX,     BLUE2_IDX,  RED_IDX ,   RED_IDX ,   RED_IDX,
		 BLACK_IDX,  WHITE_IDX,  BLUE3_IDX,  BLUE3_IDX,    RED_IDX ,  RED_IDX ,   RED_IDX ,   RED_IDX,
		 BLACK_IDX,  BLUE4_IDX,  BLUE4_IDX,   RED_IDX ,   RED_IDX ,    RED_IDX ,  RED_IDX ,   RED_IDX ,
		 BLACK_IDX,  BLUE3_IDX,  BLUE3_IDX,   RED_IDX ,   RED_IDX ,    RED_IDX ,  RED_IDX ,   RED_IDX ,
		 BLACK_IDX,  BLUE2_IDX,   RED_IDX ,   RED_IDX ,    RED_IDX ,  RED_IDX ,   RED_IDX ,   RED_IDX ,
		 BLACK_IDX,  BLUE5_IDX,   RED_IDX ,   RED_IDX ,    RED_IDX ,  RED_IDX ,   RED_IDX ,   RED_IDX ,
};
*/




void configure_graphics_main(){
	REG_DISPCNT = MODE_5_2D | DISPLAY_BG0_ACTIVE;
	BGCTRL[0] = BG_TILE_BASE(0) | BG_COLOR_256 | BG_MAP_BASE(1) | BG_32x32;
	VRAM_A_CR = VRAM_A_MAIN_BG | VRAM_ENABLE;

	BG_PALETTE[BLUE1_IDX] = ARGB16(1,0,0,13);
	BG_PALETTE[BLUE2_IDX] = ARGB16(1,1,3,31);
	BG_PALETTE[BLUE3_IDX] = ARGB16(1,0,20,29);
	BG_PALETTE[BLUE4_IDX] = ARGB16(1,19,27,29);
	BG_PALETTE[BLUE5_IDX] = ARGB16(1,0,0,20);
	BG_PALETTE[RED_IDX] = ARGB16(1,31,0,0);
	BG_PALETTE[GREEN_IDX] = ARGB16(1,0,31,0);
	BG_PALETTE[WHITE_IDX] = ARGB16(1,31,31,31);
	BG_PALETTE[BLACK_IDX] = ARGB16(1,5,5,5);
	BG_PALETTE[CYAN_IDX] = ARGB16(1,0,15,15);
	BG_PALETTE[CYAN2_IDX] = ARGB16(1,0,10,31);


	memcpy(&BG_TILE_RAM(0)[EMPTYTILE_RAM_POS], empty_tile, 64);
	//memcpy(&BG_TILE_RAM(0)[EMPTYTILE2_RAM_POS], empty_tile2, 64);
	memcpy(&BG_TILE_RAM(0)[HITTILE_RAM_POS], hit_tile, 64);
	memcpy(&BG_TILE_RAM(0)[MISSTILE_RAM_POS], miss_tile, 64);
	memcpy(&BG_TILE_RAM(0)[FULLTILE_RAM_POS], full_tile, 64);

	int i,j;

	for(i = 0; i<12; i = i + 1) //jump two rows
				for(j = 0; j < 16; j = j + 1) //jump two cols
					//BG_MAP_RAM(1)[i * 32 + j] = EMPTYTILE_IDX;

					tile_shower(EMPTYTILE_IDX, BG_MAP_RAM(1),j,i);
/*
	for(i = 0; i<12; i = i + 2) //jump two rows
			for(j = 0; j < 16; j = j + 2) //jump two cols
				//BG_MAP_RAM(1)[i * 32 + j] = EMPTYTILE_IDX;

				tile_shower(EMPTYTILE_IDX,BG_MAP_RAM(1),j,i);
*/
	tile_shower(HITTILE_IDX, BG_MAP_RAM(1),5,5);
	tile_shower(FULLTILE_IDX, BG_MAP_RAM(1),5,6);
	tile_shower(MISSTILE_IDX, BG_MAP_RAM(1),5,6);

}

void show_land(Land_status status, int x, int y){
}




const u16 V_SYM_MASK = 1<<11;
const u16 H_SYM_MASK  = 1<<10;

void tile_shower(u16 tile_index, u16* map, int grid_x, int grid_y){
	int upleft_x = grid_x*2;
	int upleft_y = grid_y*2;
	map[upleft_y * 32 + upleft_x] = tile_index;
	map[upleft_y * 32 + upleft_x+1] = tile_index | H_SYM_MASK;
	map[(upleft_y+1) * 32 + upleft_x] = tile_index | V_SYM_MASK;
	map[(upleft_y+1) * 32 + upleft_x+1] = tile_index | V_SYM_MASK | H_SYM_MASK;

}


void configure_map();
