#include "graphics_manager.h"

#define EMPTYTILE_IDX  0;
#define FULLTILE_IDX  64;
#define HITTILE_IDX  64*2;
#define MISSTILE_IDX  64*3;

enum Color_indexes {BLUE = 0, RED, GREEN, end};


void configure_graphics_sub(){

}

u8 empty_tile[64] = {
		BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
		BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
		BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
		BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
		BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
		BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
		BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,
		BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE,BLUE
};

void configure_graphics_main(){
	REG_DISPCNT = MODE_5_2D | DISPLAY_BG0_ACTIVE;
	BGCTRL[0] = BG_TILE_BASE(0) | BG_COLOR_256 | BG_MAP_BASE(1) | BG_32x32;
	VRAM_A_CR = VRAM_A_MAIN_BG | VRAM_ENABLE;


}


